# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

config:
  send_anonymous_usage_stats: False

default:
        target: dev
        outputs:
                dev:
                        type: bigquery
                        method: oauth
                        project: hortonworks-spark
                        dataset: playpen

